- name: install create-grafana-container script
  become: true
  copy:
    src: create-grafana-container.sh
    dest: "{{ prom_libexec_dir }}"
    mode: "0755"

- name: ensure grafana config directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/grafana
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/plugins
    - /etc/grafana/provisioning/dashboards
    - /etc/grafana/provisioning/notifiers

- name: install grafana config files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: grafana.ini
      dest: /etc/grafana/
    - src: prometheus.yml
      dest: /etc/grafana/provisioning/datasources/
  notify: restart grafana

- name: install grafana service
  become: true
  template:
    src: grafana.service
    dest: "{{ systemd_unit_dir }}"
  notify: reload systemd

- name: activate grafana service
  become: true
  service:
    name: grafana
    state: started
    enabled: true
