node_exporter_version: 1.1.2
node_exporter_release_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
prom_textfile_collectors:
  - script: btrfs_stats.py
    interval: 5min
  - script: nvme_metrics.sh
    interval: 5min
