- name: install weechat
  tags: [package]
  become: true
  package:
    name: "{{ weechat_packages }}"
    state: installed

- name: install weechat general configuration
  git:
    repo: "{{ weechat_config_repo }}"
    dest: ~/.weechat

- name: install weechat slack configuration
  git:
    repo: "{{ weeslack_config_repo }}"
    dest: ~/.weeslack

- name: install weeslack wrapper 
  copy:
    src: weeslack
    dest: "{{ ansible_user_dir }}/bin"
    mode: "0755"

- name: install tmuxp configuration
  git:
    repo: "{{ tmuxp_config_repo }}"
    dest: ~/.tmuxp
