- name: install weechat
  tags: [package]
  become: true
  package:
    name: "{{ weechat_packages }}"
    state: installed

- name: install weechat general configuration
  git:
    repo: "{{ weechat_config_repo }}"
    dest: ~/.weechat

- name: install weechat slack configuration
  git:
    repo: "{{ weeslack_config_repo }}"
    dest: ~/.weeslack

- name: install weechat bash configuration
  copy:
    src: weechat.bash
    dest: "{{ bash_rc_dir }}/weechat.bash"
