- name: install neovim
  tags: [package]
  become: true
  package:
    name: "{{ neovim_packages }}"
    state: installed

- name: install neovim plugins
  git:
    repo: "{{ item.url }}"
    dest: "~/.local/share/nvim/site/pack/git/start/{{ item.name }}"
    version: master
  loop: "{{ neovim_plugins }}"

- name: install neovim configuration
  git:
    repo: "{{ neovim_config_repo }}"
    dest: ~/.config/nvim

- name: ensure vim alias for neovim
  become: true
  file:
    path: /usr/bin/vim
    state: link
    src: /usr/bin/nvim

- name: install neovim bash configuration
  copy:
    src: neovim.sh
    dest: "{{ bash_rc_dir }}"
