- name: download restic
  get_url:
    url: "{{ restic_url }}"
    dest: "{{ package_cache_dir }}/restic.bz2"
  register: restic

- name: uncompress restic
  become: true
  command: bunzip2 -d "{{ package_cache_dir }}/restic.bz2"
  when: restic is changed

- name: install restic
  become: true
  copy:
    src: "{{ package_cache_dir }}/restic"
    dest: "{{ restic_bin_path }}/restic"
    mode: 0755
